### ISSUE TITLE
Support GHC 9.2.2

### ISSUE THREAD

**Issue by JKTKops** [ttuegel/pipes-ghc-events#3]
The K Haskell Backend ([downstream](https://github.com/runtimeverification/haskell-backend)) would like to move to GHC 9.2.2. This package fails to build (seems to be some type error related to `eachRow`?).

Also, hello from the team :)

**Comment by ttuegel** [comment]
I'll take try to take a look, but this might be related to [simplified subsumption](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#simplified-subsumption).

**Comment by ttuegel** [comment]
Fixed in 2004c6ea27cc532ba59ff3ea68881e58e514bbdc. It _was_ simplified subsumption, although the problem was actually in `pipes-sqlite-simple` and several other dependencies.
